
# PRO01: ¿Qué campañas comerciales se han realizado en un municipio?

PREFIX edintpro: <http://vocab.linkeddata.es/datosabiertos/def/comercio/promocion#>
PREFIX esadm:    <http://vocab.linkeddata.es/datosabiertos/def/sector-publico/territorio#>
PREFIX dcterms:  <http://purl.org/dc/terms/>

SELECT DISTINCT ?municipio ?campaign ?campaignId
WHERE {
  ?campaign a edintpro:CommercialCampaign ;
            edintpro:locatedInZone ?zone ;
            dcterms:identifier ?campaignId .

  ?zone esadm:municipio ?municipio . # También puede ser a través de edintzone:locatedIn
  
}
ORDER BY ?municipio ?campaignId
